EXECUTABLES = OpenArena/OA
LIBRARIES = 
BUILDROOT = /usr/local
PREFIX = 
INCLUDE_DIRS = /System/Library/Frameworks/OpenGL.framework/Headers
LIBRARY_DIRS = /System/Library/Frameworks/OpenGL.framework/Libraries

.Phony: all clean install

all:
	$(MAKE) -C src all
	
clean: 
	$(MAKE) -C src clean

install:
	
install-devel:
	
install-doc:
	



