EXECUTABLES = OpenArena/OA
LIBRARIES = 
BUILDROOT = /usr/local
PREFIX = 

.Phony: all clean install distclean

all:
	$(MAKE) -C src all
	
clean: 
	$(MAKE) -C src clean

install:
	
install-devel:
	
install-doc:

distclean: clean
	rm -f Makefile
	rm -f src/Makefile




