#ifdef WIN32
#include <windows.h>
#define KEY_LBUTTON	VK_LBUTTON
#define KEY_RBUTTON VK_RBUTTON
#define KEY_MBUTTON	VK_MBUTTON
#define KEY_LEFT	VK_LEFT
#define KEY_RIGHT	VK_RIGHT
#define KEY_UP		VK_UP
#define KEY_DOWN	VK_DOWN
#define KEY_SPACE	VK_SPACE
#define KEY_TAB		VK_TAB
#define KEY_RETURN	VK_RETURN
#define KEY_SHIFT	VK_SHIFT
#define KEY_PAUSE	VK_PAUSE
#define KEY_CONTROL	VK_CONTROL
#define KEY_CAPITAL	VK_CAPITAL
#define KEY_ESCAPE	VK_ESCAPE
#define KEY_PRIOR	VK_PRIOR
#define KEY_NEXT	VK_NEXT
#define KEY_END		VK_END
#define KEY_HOME	VK_HOME
#define KEY_INSERT	VK_INSERT
#define KEY_DELETE	VK_DELETE
#define KEY_LWIN	VK_LWIN
#define KEY_RWIN	VK_RWIN
#define KEY_APPS	VK_APPS
#define KEY_NUMPAD0	VK_NUMPAD0
#define KEY_NUMPAD1	VK_NUMPAD1
#define KEY_NUMPAD2	VK_NUMPAD2
#define KEY_NUMPAD3	VK_NUMPAD3
#define KEY_NUMPAD4	VK_NUMPAD4
#define KEY_NUMPAD5	VK_NUMPAD5
#define KEY_NUMPAD6	VK_NUMPAD6
#define KEY_NUMPAD7	VK_NUMPAD7
#define KEY_NUMPAD8	VK_NUMPAD8
#define KEY_NUMPAD9	VK_NUMPAD9
#define KEY_MULTIPLY	VK_MULTIPLY
#define KEY_ADD		VK_ADD
#define KEY_SUBTRACT	VK_SUBTRACT
#define KEY_DIVIDE		VK_DIVIDE
#define KEY_F1			VK_F1
#define KEY_F2			VK_F2
#define KEY_F3			VK_F3
#define KEY_F4			VK_F4
#define KEY_F5			VK_F5
#define KEY_F6			VK_F6
#define KEY_F7			VK_F7
#define KEY_F8			VK_F8
#define KEY_F9			VK_F9
#define KEY_F10			VK_F10
#define KEY_F11			VK_F11
#define KEY_F12			VK_F12
#define KEY_NUMLOCK		VK_NUMLOCK
#define KEY_SCROLL		VK_SCROLL
#define KEY_SEPARATOR	VK_SEPARATOR
#define KEY_OEM_1		VK_OEM_1
#define KEY_OEM_2		VK_OEM_2
#define KEY_OEM_3		VK_OEM_3
#define KEY_OEM_4		VK_OEM_4
#define KEY_OEM_5		VK_OEM_5
#define KEY_OEM_6		VK_OEM_6
#define KEY_OEM_7		VK_OEM_7
#define KEY_OEM_PERIOD	VK_OEM_PERIOD
#define KEY_OEM_PLUS	VK_OEM_PLUS
#define KEY_OEM_MINUS	VK_OEM_MINUS
#define KEY_OEM_COMMA	VK_OEM_COMMA
#define KEY_BACK		VK_BACK
#endif

#ifdef __linux
//I think these three are right
#define KEY_LBUTTON		XK_Pointer_Button1
#define KEY_RBUTTON		XK_Pointer_Button2
#define KEY_MBUTTON 	XK_Pointer_Button3
#define KEY_LEFT		XK_Left
#define KEY_RIGHT		XK_Right
#define KEY_UP			XK_Up
#define KEY_DOWN		XK_Down
#define KEY_SPACE		XK_KP_Space
#define KEY_TAB			XK_Tab
#define KEY_RETURN		XK_Return
#define KEY_SHIFT		10
#define KEY_PAUSE		XK_Pause
#define KEY_CONTROL		12
#define KEY_CAPITAL		13
#define KEY_ESCAPE		XK_Escape
#define KEY_PRIOR		XK_Prior
#define KEY_NEXT		XK_Next
#define KEY_END			XK_End
#define KEY_HOME		XK_Home
#define KEY_INSERT		XK_Insert
#define KEY_DELETE		XK_Delete
#define KEY_LWIN		21
#define KEY_RWIN		22
#define KEY_APPS		23
#define KEY_NUMPAD0		XK_KP_0
#define KEY_NUMPAD1		XK_KP_1
#define KEY_NUMPAD2		XK_KP_2
#define KEY_NUMPAD3		XK_KP_3
#define KEY_NUMPAD4		XK_KP_4
#define KEY_NUMPAD5		XK_KP_5
#define KEY_NUMPAD6		XK_KP_6
#define KEY_NUMPAD7		XK_KP_7
#define KEY_NUMPAD8		XK_KP_8
#define KEY_NUMPAD9		XK_KP_9
#define KEY_MULTIPLY	XK_KP_Multiply
#define KEY_ADD			XK_KP_Add
#define KEY_SUBTRACT	XK_KP_Subtract
#define KEY_DIVIDE		XK_KP_Divide
#define KEY_F1			XK_F1
#define KEY_F2			XK_F2
#define KEY_F3			XK_F3
#define KEY_F4			XK_F4
#define KEY_F5			XK_F5
#define KEY_F6			XK_F6
#define KEY_F7			XK_F7
#define KEY_F8			XK_F8
#define KEY_F9			XK_F9
#define KEY_F10			XK_F10
#define KEY_F11			XK_F11
#define KEY_F12			XK_F12	
#define KEY_NUMLOCK		50
#define KEY_SCROLL		XK_Scroll_Lock
#define KEY_SEPARATOR	52
#define KEY_OEM_1		53
#define KEY_OEM_2		54
#define KEY_OEM_3		55
#define KEY_OEM_4		56
#define KEY_OEM_5		57
#define KEY_OEM_6		58
#define KEY_OEM_7		59
#define KEY_OEM_PERIOD	60
#define KEY_OEM_PLUS	61
#define KEY_OEM_MINUS	62
#define KEY_OEM_COMMA	63
#define KEY_BACK		XK_BackSpace
#endif
