//Everything in this file will be abstracted by oa_input
//These definitions will be replaced at that time
#ifdef WIN32
#include <windows.h>
#define KEY_LBUTTON	VK_LBUTTON
#define KEY_RBUTTON VK_RBUTTON
#define KEY_MBUTTON	VK_MBUTTON
#define KEY_LEFT	VK_LEFT
#define KEY_RIGHT	VK_RIGHT
#define KEY_UP		VK_UP
#define KEY_DOWN	VK_DOWN
#define KEY_SPACE	VK_SPACE
#define KEY_TAB		VK_TAB
#define KEY_RETURN	VK_RETURN
#define KEY_SHIFT	VK_SHIFT
#define KEY_PAUSE	VK_PAUSE
#define KEY_CONTROL	VK_CONTROL
#define KEY_CAPITAL	VK_CAPITAL
#define KEY_ESCAPE	VK_ESCAPE
#define KEY_PRIOR	VK_PRIOR
#define KEY_NEXT	VK_NEXT
#define KEY_END		VK_END
#define KEY_HOME	VK_HOME
#define KEY_INSERT	VK_INSERT
#define KEY_DELETE	VK_DELETE
#define KEY_LWIN	VK_LWIN
#define KEY_RWIN	VK_RWIN
#define KEY_APPS	VK_APPS
#define KEY_NUMPAD0	VK_NUMPAD0
#define KEY_NUMPAD1	VK_NUMPAD1
#define KEY_NUMPAD2	VK_NUMPAD2
#define KEY_NUMPAD3	VK_NUMPAD3
#define KEY_NUMPAD4	VK_NUMPAD4
#define KEY_NUMPAD5	VK_NUMPAD5
#define KEY_NUMPAD6	VK_NUMPAD6
#define KEY_NUMPAD7	VK_NUMPAD7
#define KEY_NUMPAD8	VK_NUMPAD8
#define KEY_NUMPAD9	VK_NUMPAD9
#define KEY_MULTIPLY	VK_MULTIPLY
#define KEY_ADD		VK_ADD
#define KEY_SUBTRACT	VK_SUBTRACT
#define KEY_DIVIDE		VK_DIVIDE
#define KEY_F1			VK_F1
#define KEY_F2			VK_F2
#define KEY_F3			VK_F3
#define KEY_F4			VK_F4
#define KEY_F5			VK_F5
#define KEY_F6			VK_F6
#define KEY_F7			VK_F7
#define KEY_F8			VK_F8
#define KEY_F9			VK_F9
#define KEY_F10			VK_F10
#define KEY_F11			VK_F11
#define KEY_F12			VK_F12
#define KEY_NUMLOCK		VK_NUMLOCK
#define KEY_SCROLL		VK_SCROLL
#define KEY_SEPARATOR	VK_SEPARATOR
#define KEY_OEM_1		VK_OEM_1
#define KEY_OEM_2		VK_OEM_2
#define KEY_OEM_3		VK_OEM_3
#define KEY_OEM_4		VK_OEM_4
#define KEY_OEM_5		VK_OEM_5
#define KEY_OEM_6		VK_OEM_6
#define KEY_OEM_7		VK_OEM_7
#define KEY_OEM_PERIOD	VK_OEM_PERIOD
#define KEY_OEM_PLUS	VK_OEM_PLUS
#define KEY_OEM_MINUS	VK_OEM_MINUS
#define KEY_OEM_COMMA	VK_OEM_COMMA
#define KEY_BACK		VK_BACK
#endif

#ifdef __linux
enum Keys{
	KEY_UNKNOWN = 0,
	KEY_LBUTTON,
	KEY_RBUTTON,
	KEY_MBUTTON,
	KEY_LEFT,
	KEY_RIGHT,
	KEY_UP,
	KEY_DOWN,
	KEY_SPACE,
	KEY_RETURN,
	KEY_SHIFT,
	KEY_PAUSE,
	KEY_CONTROL,
	KEY_CAPITAL,
	KEY_ESCAPE,
	KEY_PRIOR,
	KEY_NEXT,
	KEY_END,
	KEY_HOME,
	KEY_INSERT,
	KEY_DELETE,
	KEY_LWIN,
	KEY_RWIN,
	KEY_APPS,
	KEY_NUMPAD0,
	KEY_NUMPAD1,
	KEY_NUMPAD2,
	KEY_NUMPAD3,
	KEY_NUMPAD4,
	KEY_NUMPAD5,
	KEY_NUMPAD6,
	KEY_NUMPAD7,
	KEY_NUMPAD8,
	KEY_NUMPAD9,
	KEY_MULTIPLY,
	KEY_ADD,
	KEY_SUBTRACT,
	KEY_DIVIDE,
	KEY_F1,
	KEY_F2,
	KEY_F3,
	KEY_F4,
	KEY_F5,
	KEY_F6,
	KEY_F7,
	KEY_F8,
	KEY_F9,
	KEY_F10,
	KEY_F11,
	KEY_F12,
	KEY_NUMLOCK,
	KEY_SCROLL,
	KEY_SEPARATOR,
	KEY_OEM_1,
	KEY_OEM_2,
	KEY_OEM_3,
	KEY_OEM_4,
	KEY_OEM_5,
	KEY_OEM_6,
	KEY_OEM_7,
	KEY_OEM_PERIOD,
	KEY_OEM_PLUS,
	KEY_OEM_MINUS,
	KEY_OEM_COMMA,
	KEY_BACK,
	KEY_TAB,
	KEY_0,
	KEY_1,
	KEY_2,
	KEY_3,
	KEY_4,
	KEY_5,
	KEY_6,
	KEY_7,
	KEY_8,
	KEY_9,
	KEY_A,
	KEY_B,
	KEY_C,
	KEY_D,
	KEY_E,
	KEY_F,
	KEY_G,
	KEY_H,
	KEY_I,
	KEY_J,
	KEY_K,
	KEY_L,
	KEY_M,
	KEY_N,
	KEY_O,
	KEY_P,
	KEY_Q,
	KEY_R,
	KEY_S,
	KEY_T,
	KEY_U,
	KEY_V,
	KEY_W,
	KEY_X,
	KEY_Y,
	KEY_Z
}
#endif
