//Everything in this file will be abstracted by oa_input
//These definitions will be replaced at that time
#ifdef WIN32
#include <windows.h>
#define KEY_LBUTTON	VK_LBUTTON
#define KEY_RBUTTON VK_RBUTTON
#define KEY_MBUTTON	VK_MBUTTON
#define KEY_LEFT	VK_LEFT
#define KEY_RIGHT	VK_RIGHT
#define KEY_UP		VK_UP
#define KEY_DOWN	VK_DOWN
#define KEY_SPACE	VK_SPACE
#define KEY_TAB		VK_TAB
#define KEY_RETURN	VK_RETURN
#define KEY_SHIFT	VK_SHIFT
#define KEY_PAUSE	VK_PAUSE
#define KEY_CONTROL	VK_CONTROL
#define KEY_CAPITAL	VK_CAPITAL
#define KEY_ESCAPE	VK_ESCAPE
#define KEY_PRIOR	VK_PRIOR
#define KEY_NEXT	VK_NEXT
#define KEY_END		VK_END
#define KEY_HOME	VK_HOME
#define KEY_INSERT	VK_INSERT
#define KEY_DELETE	VK_DELETE
#define KEY_LWIN	VK_LWIN
#define KEY_RWIN	VK_RWIN
#define KEY_APPS	VK_APPS
#define KEY_NUMPAD0	VK_NUMPAD0
#define KEY_NUMPAD1	VK_NUMPAD1
#define KEY_NUMPAD2	VK_NUMPAD2
#define KEY_NUMPAD3	VK_NUMPAD3
#define KEY_NUMPAD4	VK_NUMPAD4
#define KEY_NUMPAD5	VK_NUMPAD5
#define KEY_NUMPAD6	VK_NUMPAD6
#define KEY_NUMPAD7	VK_NUMPAD7
#define KEY_NUMPAD8	VK_NUMPAD8
#define KEY_NUMPAD9	VK_NUMPAD9
#define KEY_MULTIPLY	VK_MULTIPLY
#define KEY_ADD		VK_ADD
#define KEY_SUBTRACT	VK_SUBTRACT
#define KEY_DIVIDE		VK_DIVIDE
#define KEY_F1			VK_F1
#define KEY_F2			VK_F2
#define KEY_F3			VK_F3
#define KEY_F4			VK_F4
#define KEY_F5			VK_F5
#define KEY_F6			VK_F6
#define KEY_F7			VK_F7
#define KEY_F8			VK_F8
#define KEY_F9			VK_F9
#define KEY_F10			VK_F10
#define KEY_F11			VK_F11
#define KEY_F12			VK_F12
#define KEY_NUMLOCK		VK_NUMLOCK
#define KEY_SCROLL		VK_SCROLL
#define KEY_SEPARATOR	VK_SEPARATOR
#define KEY_OEM_1		VK_OEM_1
#define KEY_OEM_2		VK_OEM_2
#define KEY_OEM_3		VK_OEM_3
#define KEY_OEM_4		VK_OEM_4
#define KEY_OEM_5		VK_OEM_5
#define KEY_OEM_6		VK_OEM_6
#define KEY_OEM_7		VK_OEM_7
#define KEY_OEM_PERIOD	VK_OEM_PERIOD
#define KEY_OEM_PLUS	VK_OEM_PLUS
#define KEY_OEM_MINUS	VK_OEM_MINUS
#define KEY_OEM_COMMA	VK_OEM_COMMA
#define KEY_BACK		VK_BACK
#endif

#ifdef __linux
#define KEY_LBUTTON		0
#define KEY_RBUTTON		1
#define KEY_MBUTTON 	2
#define KEY_LEFT		3
#define KEY_RIGHT		4
#define KEY_UP			5
#define KEY_DOWN		6
#define KEY_SPACE		7
#define KEY_TAB			8
#define KEY_RETURN		9
#define KEY_SHIFT		10
#define KEY_PAUSE		11
#define KEY_CONTROL		12
#define KEY_CAPITAL		13
#define KEY_ESCAPE		14
#define KEY_PRIOR		15
#define KEY_NEXT		16
#define KEY_END			17
#define KEY_HOME		18
#define KEY_INSERT		19
#define KEY_DELETE		20
#define KEY_LWIN		21
#define KEY_RWIN		22
#define KEY_APPS		23
#define KEY_NUMPAD0		24
#define KEY_NUMPAD1		25
#define KEY_NUMPAD2		26
#define KEY_NUMPAD3		27
#define KEY_NUMPAD4		28
#define KEY_NUMPAD5		29
#define KEY_NUMPAD6		30
#define KEY_NUMPAD7		31
#define KEY_NUMPAD8		32
#define KEY_NUMPAD9		33
#define KEY_MULTIPLY	34
#define KEY_ADD			35
#define KEY_SUBTRACT	36
#define KEY_DIVIDE		37
#define KEY_F1			38
#define KEY_F2			39
#define KEY_F3			40
#define KEY_F4			41
#define KEY_F5			42
#define KEY_F6			43
#define KEY_F7			44
#define KEY_F8			45
#define KEY_F9			46
#define KEY_F10			47
#define KEY_F11			48
#define KEY_F12			49
#define KEY_NUMLOCK		50
#define KEY_SCROLL		51
#define KEY_SEPARATOR	52
#define KEY_OEM_1		53
#define KEY_OEM_2		54
#define KEY_OEM_3		55
#define KEY_OEM_4		56
#define KEY_OEM_5		57
#define KEY_OEM_6		58
#define KEY_OEM_7		59
#define KEY_OEM_PERIOD	60
#define KEY_OEM_PLUS	61
#define KEY_OEM_MINUS	62
#define KEY_OEM_COMMA	63
#define KEY_BACK		64
#endif
